<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="547" started-at="2016-05-13T17:42:03Z" finished-at="2016-05-13T17:42:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="547" started-at="2016-05-13T17:42:03Z" finished-at="2016-05-13T17:42:04Z">
      <class name="com.services.Testing">
        <test-method status="FAIL" signature="follow()[pri:0, instance:com.services.Testing@4348bd9]" name="follow" duration-ms="355" started-at="2016-05-13T20:42:03Z" finished-at="2016-05-13T20:42:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [{"status":1}] but found [{"status":0}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [{"status":1}] but found [{"status":0}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.services.Testing.follow(Testing.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- follow -->
        <test-method status="PASS" signature="getFollowers()[pri:0, instance:com.services.Testing@4348bd9]" name="getFollowers" duration-ms="33" started-at="2016-05-13T20:42:04Z" finished-at="2016-05-13T20:42:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getFollowers -->
        <test-method status="PASS" signature="unFollow()[pri:0, instance:com.services.Testing@4348bd9]" name="unFollow" duration-ms="120" started-at="2016-05-13T20:42:04Z" finished-at="2016-05-13T20:42:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unFollow -->
      </class> <!-- com.services.Testing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
